### ISSUE TITLE
Text overlapping on highscore screen

### ISSUE THREAD

**Issue by flokuep** [Vocaluxe/Vocaluxe#728] opened 2024-11-18 10:35 UTC
A user reported on discord that with the latest nightly the scores are overlapping on the highscore screen:

![Screenshot-2024-11-16-113318.jpg](https://github.com/user-attachments/assets/b2caec73-4788-4057-9158-e3bd84104790)

This only happens with medleys, might be introduced with #714.

**Comment by flokuep** [comment] 2024-11-18 10:36
@Rap-Voca could this be introduced with #715 (full HD support)? It would be cool if you could have a look at it...

**Comment by ghost** [comment] 2024-11-18 18:38
I looked into it. Here’s what I discovered:

At first glance, it seemed that the problem might be caused by insufficient space for displaying points and the date, which could be resolved by adjusting the theme files. However, that doesn’t appear to be the case.

After playing a medley song, the issue spreads to other screens as well—for example, the song length on the song selection screen also becomes affected. Even playing a normal song afterward doesn’t resolve the issue; the problem persists.

It seems that once you play a medley, something goes wrong and remains that way until the program is restarted.

Unfortunately, I don’t have any insights into what might be causing this issue. Perhaps someone else might have some insights?

**Comment by flokuep** [comment] 2024-11-18 19:01
Okay that's really strange. Do you have a screenshot of the song selection screen? Could you identify the text that is shown? And could you check the state just before adding full HD support if that one is affected too?

**Comment by ghost** [comment] 2024-11-18 22:08
Here is the screenshot:
![Screen](https://github.com/user-attachments/assets/ca3cca10-1ea7-4882-ae33-721e6ffd9346)

**Comment by flokuep** [comment] 2024-11-19 07:11
It looks like it is only affecting digits. There is a compile flag, `FONT_DEBUG_OUTPUT` that could be enabled to generate bitmaps of every char into the vocaluxe folder. Would be interesting to see if the digits are rendered correctly.

**Comment by flokuep** [comment] 2024-11-19 08:22
Some ideas:

- CFontStyle.GetOrAddGlyph: We're limiting the height here and do some calculations (don't ask me why). Maybe something is wrong here.

This part of code is used to calculate the height and width of a glyph (single character or number), which is relevant to have the strings placed in line (which is kind of broken for everything excepcts alphabetical characters).

**Closed as completed** 2024-11-20 16:59 UTC
Labels: bug
