### ISSUE TITLE
errors, when controller disconnects while vocaluxe is running

### ISSUE THREAD

**Issue by mandark** [Vocaluxe/Vocaluxe#196] opened 2016-02-04 12:55 UTC
sometimes (although not always) vocaluxe throws an error, when a controller is disconnected (either due to inactivity or by turning it off) while vocaluxe is running.

i've had this problem with the most recent nightly version of vocaluxe as well as several previous versions. also i was able to reproduce this error with both an X360 wireless controller as well as a xbox ONE controller, both on win7x64.

here are screenshots of the errors:
http://imgur.com/pseB1M9
http://imgur.com/95gUibh

after confirming the first error, the second error is shown, and after confirming that one, vocaluxe crashes.

**Comment by lukeIam** [comment] 2016-02-06 09:06
I'm a bit confused that the error message says `CController.Update()`.
Because all controller querying is done in `CGamePad._MainLoop()` or `CGamePad._HandleButtons()`.

Here will be some debugging required, but unfortunately I do not have any controller here...

**Comment by flokuep** [comment] 2016-02-06 10:59
I guess I could get hands on a controller; Could try this after my exams.

**Comment by lukeIam** [comment] 2016-02-07 13:57
The debug output shows some `"System.DllNotFoundException" in OpenTK.dll` during Vocaluxe start

**Comment by lukeIam** [comment] 2016-09-09 16:14
@mandark is this problem still existing in the current nightly?

I tried connecting/disconnecting my x360 controller and receiver several times in different screens -> everything worked fine.

BTW: is there any reason why "back" is "X"(left) instead of "B"(right) (the normal back button in most games)

**Comment by lukeIam** [comment] 2016-11-13 13:56
@mandark 
I will close this issue - if the problem is still exits I will reopen it.

**Closed by lukeIam** 2016-11-13 13:56 UTC
Labels: bug
