### ISSUE TITLE
Missing singer in Highscore overview

### ISSUE THREAD

**Issue by Michri** [Vocaluxe/Vocaluxe#351] opened 2017-12-20 21:51 UTC
When playing with 4 people (2 microphones) Vocaluxe 'Blue Sunrise' 0.4.0 (x64) (0.4.0-160-gee60af4) (281 songs) in different modes, we had sometimes the issue that Highscore overview shows only one singer instead of both.

**Comment by flokuep** [comment] 2017-12-21 05:51
Please check if these profiles aren't guest profiles. If these are, this is the correct behaviour

**Comment by Michri** [comment] 2017-12-22 21:17
Right, we had guest profiles in there as well.
What'S the reason, for keeping them out?

**Comment by flokuep** [comment] 2017-12-26 09:36
No bug, duplicate of #350

**Closed by flokuep** 2017-12-26 09:36 UTC
