### ISSUE TITLE
Browsing Playlist is showing wrong Titles

### ISSUE THREAD

**Issue by Michri** [Vocaluxe/Vocaluxe#209] opened 2016-08-11 12:33 UTC
When browsing through the playlists in tilte view mode, the playlist details on right hand side show always the details of the wrong playlist. It seems, like the content of the playlist following 3 times behind the selected one are shown:

![image](https://cloud.githubusercontent.com/assets/20970069/17588585/62b2d48a-5fd0-11e6-85ec-0e54f43de28c.png)

**Comment by flokuep** [comment] 2016-08-11 13:37
I can't reprocude this... Are you using our latest nightly build?

Maybe it isn't a bug: The select-slide in the left menu is for opening playlists. You need to click on selected playlist or press enter when it's selected...

**Comment by Michri** [comment] 2016-08-11 15:07
That is as I did it: Browsing through playlists with arrow-keys and then select by pressing enter.

As I am not an developer expert, I downloaded the  precompiled Windows binaries (nighly builds) (https://github.com/Vocaluxe/Vocaluxe/releases), bit these files are dated with 1st April 2016  :-(
I have tested x86 and the x64 version.

I am quite new in Vocaluxe and I wonder about:
 - How to get easily the latest nightly build (as binary)?
 - Where can I even post some other questions? Is there some forum for questions? Like: How to adjust microphone sensitivity? How to use delay-test for microphones? etc.

Thanks for any kind of help.

**Comment by lukeIam** [comment] 2016-08-11 16:31
Hi Michri,

that's how it looks for me:
![playlist](https://cloud.githubusercontent.com/assets/5115160/17596222/b4431114-5ff0-11e6-9cd2-1be18718541d.gif)

> How to get easily the latest nightly build (as binary)?
Unfortunately we haven't had much time to work on Vocaluxe in the recent past - so the 1st April version (0.3.0.83-638-gd01ac27) is the latest nightly build.
If there will be a new one you will find it there: https://github.com/Vocaluxe/Vocaluxe/releases

> Where can I even post some other questions? Is there some forum for questions?
There is a (german) forum here: http://forum.ultra-star.de/viewforum.php?f=89
But there are already some English threads there, so feel free to post in English there.

> How to use delay-test for microphones?
Just click the Delay-Test button while having microphones attached and speakers on.
You hear a beep and Vocaluxe should calculate the delays automatically.

**Comment by Michri** [comment] 2016-08-11 18:19
Hi lukeIam,

as shown in your video, that is what I have expected.
Are you using the same build as I do (from the "nightly" build)? - in my case it is from 1st of April (during Vocaluxe start following is shown: Vocaluxe "Shining Heaven" v0.3.0 (x64) Beta (0.3.0.83-638-gd01ac27) )

For me in this build the the playlist feature doesn't work properly. BTW: I have about 27 playlists defined and about 750 songs in there.

Thanks for the hint about the forum. German is no problem, as I am German, but I wasn't sure about how to report issues, as ohers have been reported in English.

About delay test on microphones: What should happen as result when triggering the test? After the test I still see question marks for each enabled microphone and for only one of my two mics I see a bar-graph. 

How can I configure any kind of gain on the microphones? In UltraStarDeluxe (1.0.1a) I am able to define mic gain in the sound-options (off; +6dB; +12dB;+18dB) and noice canceling ("Rauschunterdrückung") can be configured as well. Any chance on that in Vocaluxe? (I can of course ask this in the forum as well)

**Comment by Michri** [comment] 2016-09-18 10:13
Ich habe gerade das letzte nightly build heruntergeladen (11.09.2016). Hier tritt noch immer das selbe Problem auf.
Ich habe zum Testen jetzt einmal die Anzahl der Playlists reduziert (von 27 auf 6 ; bei 765 Musiktiteln). Dann scheint's zu funktionieren.
Ich verwende allerdings Playlist-Formate aus Ultrastar (.upl). Diese scheinen in xml konvertiert zu werden.
Ich habe jetzt einmal schrittweise meine Playlisten kopiert. Sobald ich 20 oder mehr Listen einfüge. Scheint die Playlistenfunktion durcheinanderzukommen.
Gibt es eine Beschränkung in der Anzahl?

**Comment by Michri** [comment] 2016-09-25 05:50
Shall I write in English?

Can somebody confirm this problem?

**Comment by lukeIam** [comment] 2016-09-28 15:53
I created 22 playlists with 1-2 songs and one with ~250.
=> Basically it is working for me but I found two smaller problems:

1. Scrolling issue (#217)
2. If a playlist ( != the first) is selected and the left menu is closed and reopened the selector is showing the first playlist again (the you have situation like in your screenshot)

Does this explain your problem?

Example for the 2nd problem:
![playlists](https://cloud.githubusercontent.com/assets/5115160/18921121/e23e1fea-85a3-11e6-807b-5732ea7d1b69.gif)

We should think about making the playlist-selection/menus more consistent.

**Comment by lukeIam** [comment] 2016-09-28 15:57
> How can I configure any kind of gain on the microphones? In UltraStarDeluxe (1.0.1a) I am able to define mic gain in the sound-options (off; +6dB; +12dB;+18dB)

I suggest to use the microphone settings of windows:
![image](https://cloud.githubusercontent.com/assets/5115160/18921414/fab13322-85a4-11e6-8cbd-5f2614a229db.png)

**Comment by Michri** [comment] 2016-09-28 16:02
How are you creating the videos? Then I can show it in the same way.

**Comment by lukeIam** [comment] 2016-09-28 16:11
> How are you creating the videos?

https://screentogif.codeplex.com 
(resize before export - it has to be smaller then 10MB for uploading it to GitHub)

**Comment by Michri** [comment] 2016-09-28 20:09
I am not able to generate a video smaller 10MB :-(

For me it behaved completely different. Most times the shown playlist isn't fitting to the selected one :-(

**Comment by Michri** [comment] 2016-10-01 06:27
Hi, 
I figured out another issue:
Sometimes I get a different title played than I selected from the shown playlist on the right hand side. When this problem appears, it can only be solved by restarting VocaLuxe. This problem even can appear with just having one playlist with just a few titles in it.
I wonder that it appears spontaneously.

**Comment by lukeIam** [comment] 2016-11-19 19:35
After a lot of trying I found something that is reproduce-able:

- 2 Vocaluxe playlists (`1`, `2`)
- 3 Ultrastar playlists (`Test 1`, `Test 2`, `Test 3`)
- Delete `Test 2`
- Open all playlists
    - `1`, `2`, `Test 1` are working
    - `Test 3` can't be opened

**Comment by lukeIam** [comment] 2016-11-20 10:22
I think I found the reason:

Playlists get an readonly (ascending) integer id assigned on loading.
The selection of playlists works with an interval `[0, playlists.length-1]`.

If we delete one playlist in between, the selection interval gets adjusted, but the playlist-ids stay the same.

**Comment by lukeIam** [comment] 2016-11-21 19:13
@Michri @derivator: Please test: #230

**Comment by Michri** [comment] 2016-11-21 20:08
Is that fix part of the nightly build?

**Comment by lukeIam** [comment] 2016-11-21 20:42
It will get part of "The Nightly Build" if it's tested (and fixed).

There is only one real "Nightly": https://github.com/Vocaluxe/Vocaluxe/releases/tag/Nightly
It represents the latest state of developement (but it does not contain untested fixes/features)

But we our build system is also building some other versions (there are not called nightlies to avoid confusion):

- Every PR
![image](https://cloud.githubusercontent.com/assets/5115160/20499405/af440b1e-b031-11e6-8b13-41974d0ba01e.png)
- Every released version/tag (I hope we have more of them in the future 😉 )
- Every Branch of [Vocaluxe/Vocaluxe](https://github.com/Vocaluxe/Vocaluxe/branches)
- Every Branch of every fork which owner as enabled it at appveyor [**WARNING**: unofficial builds] .
E.g. all of my personal (new) Branches: [lukeIam/Vocaluxe](https://github.com/lukeIam/Vocaluxe/branches)
![image](https://cloud.githubusercontent.com/assets/5115160/20499359/765076da-b031-11e6-91cb-d85b59172829.png)



So to answer your question: 
you can either use the build from the [PR ](https://ci.appveyor.com/project/VocaluxeBuildBot/vocaluxe/build/87-lklwtosq) (static link) or from [my branch](https://ci.appveyor.com/project/lukeIam/vocaluxe/branch/FixedPlaylist) (dynamic link to the latest build of this branch) to test.

**Comment by Michri** [comment] 2016-11-23 21:31
I am a little confused right now, as I am not an developer expert.
How can I get the test version in place?

**Comment by flokuep** [comment] 2016-11-24 09:59
Just use this link (copied from above) https://ci.appveyor.com/project/lukeIam/vocaluxe/branch/FixedPlaylist

**Comment by lukeIam** [comment] 2016-11-24 16:07
> Just use this link (copied from above) https://ci.appveyor.com/project/lukeIam/vocaluxe/branch/FixedPlaylist

`Platform: x86`/`Platform: x64` -> `ARTIFACTS`

**Comment by Michri** [comment] 2016-11-24 21:38
I just checked it.
Looks good!!!
That fixseem to solve the issue.
Would be great to get it into the offical code.

Thanks

**Comment by flokuep** [comment] 2016-11-25 07:59
Merged it into Vocaluxe/develop.

**Closed by flokuep** 2016-11-25 07:59 UTC
Labels: bug
