### ISSUE TITLE
New Song ID:s in the highscore database

### ISSUE THREAD

**Issue by daggeg** [Vocaluxe/Vocaluxe#463] opened 2020-01-20 05:53 UTC
I just noticed some strange shit regarding the highscore sql file.  After we sang on Saturday songs had been given new song ID:s meaning  that the old highscores couldn't be found by the game while it seems to have restructured the sql database somewhat. Not fun.

**Comment by Stefan1200-de** [comment] 2020-01-20 17:56
Can you send me the current **HighscoreDB.sqlite** file? Maybe, if you have, also an older backup, where everything is okay?

**Comment by daggeg** [comment] 2020-01-20 17:57
It looks like the sql highscore database and its' songs table has been totally restructured. It looks pretty clear that the new song ID:s that Vocaluxe has given is in the order of the song folder.
![image](https://user-images.githubusercontent.com/6724256/72748093-a2d24f80-3bb6-11ea-923f-c42f9c8489d3.png)

**Comment by daggeg** [comment] 2020-01-20 18:01
In the new database no scores are registered at all!

**Comment by Stefan1200-de** [comment] 2020-01-20 18:59
If I copy over my HighscoreDB.sqlite from my 0.4.1 version to the newest nightly, all my highscores are still there and visible ingame. I don't know why your HighscoreDB.sqlite was broken.

**Comment by Stefan1200-de** [comment] 2020-01-21 05:48
Also using your old working highscore file with the current nightly. If I open up the highscore from a song, which I also have, I can see all your highscores without problem.

I'm unable to reproduce that problem, even with the song reloading code.

**Comment by Stefan1200-de** [comment] 2020-01-25 08:24
Still not able to reproduce with the same files.

**Comment by daggeg** [comment] 2020-01-26 20:51
Ok, it most likely was the human factor then.

**Comment by Stefan1200-de** [comment] 2020-01-27 06:12
I close this for now. If this happens again, please report back to me.

**Closed by Stefan1200-de** 2020-01-27 06:12 UTC
Labels: need feedback
