### ISSUE TITLE
Crash with bad genre in video metadata

### ISSUE THREAD

**Issue by pulseb** [Vocaluxe/Vocaluxe#406] opened 2018-12-29 00:06 UTC
**_Behavior:_**
In the song selection, when the specific video start, it crashes Vocaluxe.exe with no message.
OS Logs tell crash occurs from acinerella.dll
The same song works well in UltraStar Deluxe.

**_Steps to reproduce:_**
1. Have an mp4 videoclip with metatag genre filled with:
`genre: -.--.--.--.--.--.--.--.--.--.--.--.--.--.--.--.--.--.--.--.--.--.--.--.-`
(add it with VLC for exemple)
2. Go in the song selection with video preview.
3. Select the "corrupted" song
--> freeze 1 second then back to desktop

**_Workaround:_**
As workaround we can remove the genre tag with VLC to make the videoclip working, but as it works well with Ultrastar, I think it could works in Vocaluxe.

**Comment by flokuep** [comment] 2018-12-29 09:01
USdx doesn't use acinerella, so might be a issue in this library. Will check, if we could do some workaround...

**Comment by Stefan1200-de** [comment] 2020-01-13 21:28
First: I can reproduce it, as soon as I put more than **32 bytes** (= characters) into this **genre** field.

I debugged this crash. To make sure, if I could create a workaround for it, I watched every step of Vocaluxe using Visual Studio. I get to the line 273 in the CAcinerella.cs file from Vocaluxe without crash. https://github.com/Vocaluxe/Vocaluxe/blob/develop/Vocaluxe/Lib/Video/Acinerella/CAcinerella.cs#L273
As soon as we dive into the **acinerella.dll** file / **ac_open_file()**, which never comes back -> crash. My Visual Studio debugger can't follow into the acinerella.dll library, so I don't know the exact position of the crash.

But my guess: This happens within the acinerella.dll file, it uses a 32 byte buffer to save the value for the genre, look here:
https://github.com/Vocaluxe/Vocaluxe/blob/develop/Vocaluxe/Lib/Video/Acinerella/acinerella.c#L372

I think Vocaluxe use an older version of this acinerella library. Maybe this bug is already fixed. But my knowledge about the good old C language is bad at best. Maybe someone can help me with this?
That is the link to the current source of acinerella: https://github.com/astoeckel/acinerella/blob/master/src/acinerella.c#L385
I see, that it still use a 32 byte buffer, but they changed the cpymetadata() function, where I guess the source of the problem.

@lukeIam I guess you created the current acinerella.dll file, which Vocaluxe use (because I saw the old acinerella issue with the Visual Studio question ;))? Are you able to create another one with the current source code of acinerella? If you don't have time for that, I will try your "manual" at https://github.com/astoeckel/acinerella/issues/3#issuecomment-267663475 ;)

**Comment by lukeIam** [comment] 2020-01-15 17:40
Hi @Stefan1200-de ,

yes I created the version currently used acinerella.
Vocaluxe was using an adapted version and the original was not longer developed.
So I decided to fork it and fixed some problems, updated it to a newer ffmpeg version and moved some functionality from Vocaluxe (managed) to acinerella (unmanged) to gain more performance.
This version can be found here:
https://github.com/lukeIam/acinerella/tree/Vocaluxe_Adjustments2

I just checked the repo of the original version and it seems that somebody contributed to it since then. It would be worth a try to port those changes. But I can't promise anything or give a timeline...

**Comment by Stefan1200-de** [comment] 2020-01-15 19:05
@lukeIam Sounds nice, thanks. Drop me a line if I can test something.

In long term it would be nice to get the DAR value from ffmpeg, which acinerella don't have currently (only the SAR value currently), but my C knowledge is to bad for that. So I just do the C# stuff from Vocaluxe. :) If you have more time someday in the future, it would be nice if you can implement it. I can implement that on the C# Vocaluxe side then.

**Comment by Stefan1200-de** [comment] 2020-01-18 07:07
@lukeIam btw. how complex would it be to upgrade ffmpeg to a newer version, if you already have to put your hands on acinerella (sometimes, if you have a little bit time)?

My suggestion with the DAR value is much less important than upgrading ffmpeg, because of security related stuff and of course supporting newer video codecs, etc.

**Comment by lukeIam** [comment] 2020-01-18 12:39
I'm on it...

**Comment by lukeIam** [comment] 2020-01-18 14:46
tried for several hours but can not get it running with ffmpeg 4.2 - I will try again when I have time again...

**Comment by Stefan1200-de** [comment] 2020-01-18 14:53
@lukeIam Thanks for trying and have a nice weekend.

**Comment by lukeIam** [comment] 2020-01-19 14:32
interesting: the acinerella demo app works with with my modifications and ffmpeg 4.2 - but it fails playing videos in vocaluxe. hmm...

**Comment by Stefan1200-de** [comment] 2020-01-19 14:35
Can I help somehow?

**Comment by lukeIam** [comment] 2020-01-19 14:47
> Can I help somehow?

not at the moment thanks!
Somehow av_read_frame() seems to fail...

**Comment by lukeIam** [comment] 2020-01-19 16:45
Got it running 🎉

**Comment by lukeIam** [comment] 2020-01-19 17:33
https://github.com/lukeIam/acinerella/tree/Vocaluxe_Adjustments3
with
https://github.com/lukeIam/Vocaluxe/pull/new/newAcinerella42

Please remember while testing: nuget will override `Output\libs\unmanaged\acinerella.dll` on every build.

Acinerella pre-build binaries (toolset v141 x64+x86 release build with debug info):
https://drive.google.com/open?id=1o7009U_RVwo4gRGnj-PzdBhBbcY0OZWK

**Comment by lukeIam** [comment] 2020-01-19 17:39
@Stefan1200-de please let me know if it works for you

**Comment by lukeIam** [comment] 2020-01-19 17:42
ahh I just saw the reason of this issue - the genre is still limited to 32 byte (should I try to change that? or just prevent the crash?)

**Comment by Stefan1200-de** [comment] 2020-01-19 18:08
> ahh I just saw the reason of this issue - the genre is still limited to 32 byte (should I try to change that? or just prevent the crash?)

if the crash still occure, would be nice to prevent it. 32 byte should be enough for a real genre.

**Comment by lukeIam** [comment] 2020-01-19 18:13
> if the crash still occure, would be nice to prevent it.

it should be fixed in the new version -> at least my test file was preview and playable

**Comment by Stefan1200-de** [comment] 2020-01-19 19:34
> it should be fixed in the new version -> at least my test file was preview and playable

I can confirm that. My 0.4.1 fork and the current nightly crash with my test file, but a patched Vocaluxe with your changes don't crash anymore and play that video without problems. 👍

**Closed** 2020-02-10 19:54 UTC
Labels: bug
