### ISSUE TITLE
Bug in Party-Mode when using Playlist

### ISSUE THREAD

**Issue by Michri** [Vocaluxe/Vocaluxe#490] opened 2020-02-07 21:44 UTC
Hi,
I was using nightly build (5ac791c ; 5. February 2020).
When playing Party:
Party > Challenge Mode > Song source = Playlist
I noticed strange behaviours:

1. Strange overlapping of Playlist names - see screenshot.
![image](https://user-images.githubusercontent.com/20970069/74067467-a3157c00-49f9-11ea-8332-18564f4447bf.png)

2. Selecting a playlist should play titles of the selected playlist and not other playlists.
Seems like always the titles of the playlist being 3 positions behind the selected playlist are used.
Example:
Existing playlists: Playlist 1 , Playlist 2, Playlist 3 , Playlist 4, Playlist 5, Playlist 6 
Selecting Playlist2
Voclauxe is playing Playlist5

Anything to be adjusted?

**Comment by Stefan1200-de** [comment] 2020-02-07 22:04
I'm unable to reproduce the second issue, but I see the first issue on my end too.
Can you send me the contents of the **Playlists** folder (maybe compressed as ZIP)? I would be able to see the playlist name and songs on the playlists.

**Comment by Michri** [comment] 2020-02-07 22:31
@Stefan1200-de 
[Playlists.zip](https://github.com/Vocaluxe/Vocaluxe/files/4173168/Playlists.zip)

**Comment by Stefan1200-de** [comment] 2020-02-08 07:35
With your playlists I can reproduce that issue.

Offtopic:
The playlists SingStarAnthemsDiscoKlassiker.xml and SingStarAnthem.xml are the same.

**Comment by Stefan1200-de** [comment] 2020-02-08 09:33
Both bugs fixed in the next nightly.

**Closed** 2020-02-08 10:20 UTC
Labels: bug

**Comment by Michri** [comment] 2020-02-09 14:53
Great, thanks.
Done
