### ISSUE TITLE
Problems with defining teams

### ISSUE THREAD

**Issue by Michri** [Vocaluxe/Vocaluxe#350] opened 2017-12-20 21:32 UTC
When playing with 4 people (2 microphones) Vocaluxe 'Blue Sunrise' 0.4.0 (x64) (0.4.0-160-gee60af4) (281 songs) in different modes, we had trouble with defining the teams:

First two players are never removed from player-pool:

![selectplayer](https://user-images.githubusercontent.com/20970069/34229755-afab5f6e-e5d5-11e7-8053-4161ab835a5f.jpg)

It affects Challenge Mode as well as Tic-Tac-Toe.

**Comment by flokuep** [comment] 2017-12-21 05:50
Please check if these profiles aren't guest profiles. If these are, this is the correct behaviour.

**Comment by Michri** [comment] 2017-12-22 21:19
You are right. Guest profiles remain in the player-pool.
What's the reason for it?

**Comment by flokuep** [comment] 2017-12-23 12:55
We wanted to have some profiles for an easy quick-start 'experience', so you don't have to add profiles if you don't need highscore saving. But yeah, there is some space for improvements (see #354).

**Comment by lukeIam** [comment] 2018-02-14 14:55
The problem is "solved" -> closing this

**Closed by lukeIam** 2018-02-14 14:55 UTC
