### ISSUE TITLE
Crash when song browsing

### ISSUE THREAD

**Issue by skyli91** [Vocaluxe/Vocaluxe#206] opened 2016-06-13 08:08 UTC
I had a crash 4 times in a long night. It's not bad but i think this should be fixed. Sadly I didn't make any screenshots and only the newest log is saved i think, so the error log is gone.
Is anyone else experiencing these crashes? They are not so frequent.

"Shining Heaven" v0.3.0 (x64) Beta (0.3.0.83-638-gd01ac27)

![image](https://cloud.githubusercontent.com/assets/7442913/16004852/78ac55ee-3164-11e6-9121-0ef2290694b5.png)

"Unhandled exception at 0x00007FFABABDE6FC (ntdll.dll) in Vocaluxe.exe: 0xC0000374: Egy halom sérült (parameters: 0x00007FFABAC322B0)." 

from error.log:
"350) Error opening video file (can't find decoder): C:\Dalok\Japán\Egoist - Departures -Anata ni Okuru Ai no Uta- (TV)\Egoist - Departures -Anata ni Okuru Ai no Uta- (TV).mp4" 

And after restart, I can play the song with the video too, without crash. (the error happens randomly, not only on this song)

**Comment by skyli91** [comment] 2016-06-13 11:34
Can it be becouse i have no gstreamer installed on this pc? I thought it's no longer required.

**Comment by JPGsProfil** [comment] 2016-06-28 14:43
same problem here, crash during song browsing. Only some times and no specific songs. One day it crashed after 20 minutes, the other day vocaluxe ran 3 hours without crash. The Screenshot isn't from the last build, but the problem also occur in the current. Hope it helps to fix the problem.

![fehler1](https://cloud.githubusercontent.com/assets/4520514/16419646/cc3ac5c4-3d4e-11e6-83a0-2ed43127552b.jpg)
![fehler2](https://cloud.githubusercontent.com/assets/4520514/16419654/d16ef1be-3d4e-11e6-8f69-76c73d3a9c01.jpg)

**Comment by skyli91** [comment] 2016-07-01 07:53
Sorry for the late reply:

The ffmpeg error log for this video where vocaluxe crashed one time: 
"Unrecognized option 'Anata'.
Error splitting the argument list: Option not found"

Mediainfo:
Format                                   : MPEG-4
Codec ID                                 : isom (isom/avc1)
File size                                : 18.1 MiB
Duration                                 : 1mn 33s
Overall bit rate                         : 1 631 Kbps

Video
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 6 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 1mn 33s
Bit rate                                 : 1 622 Kbps
Maximum bit rate                         : 3 225 Kbps
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) fps
Original frame rate                      : 23.976 (23976/1000) fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.073
Stream size                              : 18.1 MiB (100%)
Title                                    : Video
Writing library                          : x264 core 119 r2106 07efeb4
Encoding settings                        : cabac=1 / ref=6 / deblock=1:1:1 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=0.40:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=3 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=96 / keyint_min=9 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=2pass / mbtree=1 / bitrate=1622 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=20000 / vbv_bufsize=25000 / nal_hrd=none / ip_ratio=1.40 / aq=1:0.60

**Comment by skyli91** [comment] 2016-07-01 07:56
JPGsProfil: Do you also have accents in folder names? like "Apr**é**s" as i have a folder name "Jap**á**n"

**Comment by JPGsProfil** [comment] 2016-07-01 18:09
Maybe. But can't say for sure because yesterday it worked an hour without crashing and without renming the folder with the current build. Today I removed the accent. As you said it isn't a bad problem because it only happens sometimes and in song menu. I will try the current build and report when this will happen again with accent removed.

**Comment by lukeIam** [comment] 2016-09-07 12:43
@skyli91 @JPGsProfil any news on this?

**Comment by lukeIam** [comment] 2016-11-13 13:49
@skyli91 @JPGsProfil 
I will close this issue - if the problem is still occurring I will reopen it.

**Closed by lukeIam** 2016-11-13 13:49 UTC
Labels: bug
