### ISSUE TITLE
Support for OS X / Linux

### ISSUE THREAD

**Issue by seb90** [Vocaluxe/Vocaluxe#502] opened 2020-02-19 09:25 UTC
Is there currently a goal to support Mac OS X and Linux?

I just think the new Raspberry Pi devices would be perfect environment for a Vocaluxe system.
Maybe for the start just a finished image?

And there is also a great need for Mac OS X. Unfortunately, the old UltraStar Deluxe version, which is available for Mac OS X, is anything but not running clean.

**Comment by Stefan1200-de** [comment] 2020-02-19 09:30
Well, the problem is, the developers who have time have no experience in it, others who might have the experience have no time, to make this project fully compatible with other operating systems. If there are developers, who wants to help, feel free.

**Comment by marwin89** [comment] 2024-01-20 18:15
I made two separate issues for that 
- #673
- #672 
I talked with a software engineer a week ago who is a linux expert. Maybe he has time for that in summer. But as stefan says all developers can feel free to help with that anytime. I close this.

**Closed** 2024-01-20 18:42 UTC
Labels: linux, help wanted
