### ISSUE TITLE
Feature request: limiting title list to a playlist 

### ISSUE THREAD

**Issue by Michri** [Vocaluxe/Vocaluxe#218] opened 2016-10-01 06:33 UTC
When using the simple sing mode, where all titles are shown in the center area of the screen, It would be nice to be able to limit the shown titles in the c noted area to a selected playlist, as the Center area is more nicer and provides more features than a shown playlist on the right hand side.
Or is that already possible?

**Comment by flokuep** [comment] 2016-10-03 19:02
Currently not possible an needs some more work. An 'easy way' would adding a Playlist-option to sorting. I guess for this we need to store according playlists in songs itself, but this feels a bit ugly?

**Comment by derivator** [comment] 2016-10-19 14:43
I think a good way to do it would be to add functionality to CSongFilter, since that way we can still choose how we want to sort the filtered list, and we don't need to store anything new in the songs themselves. I will attempt to implement this.

**Comment by Michri** [comment] 2016-10-19 15:08
Cool! How can I get informed about it, when it is done? And how/where can I get the adjusted code? Will it then be part of the "nightly" build?

**Comment by derivator** [comment] 2016-10-19 18:22
@Michri I will post about it here, and when it's done and merged (if we decide it should be), then it'll be in the nightlies, yes.

**Comment by derivator** [comment] 2016-10-21 20:57
I've laid the groundwork for this feature [here](https://github.com/derivator/Vocaluxe/commit/6799768e351480109afb04c3dd8b8d98b8c3e515), but there's no way to activate it yet, because I'm not very familiar with the gui code in Vocaluxe. For the challenge party mode (#222) we could probably do something similar to the other party modes.
For the simple "Sing" mode I'm not sure what the best way to do it would be. A selection in the game options seems kind of ugly to me, since you might want to change this setting often. One idea I've had was to add a key similar to the search key (F3) that would toggle between showing all songs and only the currently selected playlist. Another issue that will have to be addressed is the fact that if you limit the main view to a playlist, then select a different playlist to show on the right hand side panel, clicking the empty panel causes the game to crash with a nullpointer exception.

**Comment by Michri** [comment] 2016-10-23 18:17
Maybe somebody can help better than me, as I am not an real developer expert.

Having this feature in would be at least great!

**Comment by Stefan1200-de** [comment] 2020-01-30 19:21
Not sure if I understand this request, but I added some more possibilities to search for songs with #432, feel free to check out the current nightly.

**Comment by daggeg** [comment] 2020-01-30 19:26
I think Michri only wants to see the songs he has got on a particular playlist.  Not as a playlist made out of text in the right margin.

**Comment by Michri** [comment] 2020-01-30 19:37
yes, exactly. It is about limiting the songs to playlist-songs.

**Comment by Stefan1200-de** [comment] 2020-01-30 19:41
I still don't understand it. You just need a possibility to view the songs of a particular Vocaluxe playlist?

**Comment by Stefan1200-de** [comment] 2020-01-30 19:51
I think now I'm get it.
Whats wrong with the list that will be provided by displaying the playlist itself? Or do you just need the possibility to sing single songs from the playlist, without the need to sing the whole playlist?

**Comment by Stefan1200-de** [comment] 2020-01-30 19:59
> yes, exactly. It is about limiting the songs to playlist-songs.

Wait, limiting to songs from a single playlist, or show songs which are in a playlist, no matter which playlist?

**Comment by Michri** [comment] 2020-01-30 20:08
Right now, when selecting a playlist, the playlist-songs are shown in a separate bar on the right hand side and you need to select a song from this bar. In the center area always all available songs are shown.  It would be great, to limit the shown songs in center-area to a playlist.
This allows it so browse through songs of a dedicated playlist again and again without selecting the playlist agian.

![image](https://user-images.githubusercontent.com/20970069/73486057-99aa6500-43a4-11ea-8c7e-be791ad25881.png)

**Comment by Stefan1200-de** [comment] 2020-02-02 21:24
@Michri How you like the newest changes?
Download the newest nightly, open a playlist on the song screen and press CTRL+L

**Comment by Stefan1200-de** [comment] 2020-02-05 07:28
@Michri Now there is also a button on the bottom toolbar of a playlist to toggle the song list display:
![image](https://user-images.githubusercontent.com/15168351/73740878-5efc5000-4749-11ea-97a5-7b7386eb4b2e.png)
![image](https://user-images.githubusercontent.com/15168351/73740942-805d3c00-4749-11ea-8d0d-a88e3515ca46.png)

Please write to me, if you need improvements here.

Thanks to @derivator for the work on the filter stuff in 2016.

**Closed by Stefan1200-de** 2020-02-05 07:28 UTC
Labels: feature request

**Comment by Michri** [comment] 2020-02-05 20:59
Hi @Stefan1200-de ,
cool, new features. I just downloaded the last nightly build (5ac791c ; 5. February 2020). I noticed new features: In "Sing"-section there is a sub-menu at the bottom. Really great idea and cool features!!!

Some comments:
1. sometimes keyboard entries are not recognised
2. CTRL+# (change song sorting) isn't working at all
3. CTRL+T (change category view) is a switch to artis grouping, right? "Category" sounds confusing.
4. Search (CRTL+F or CTRL+F3) should search for the "categories" (artists), when being used in the artist/category view
5. CTRL+S (Medley) is is not always appearing, when pushing the keys on keyboard. And I wonder what the basis for a medley is, as I get always only the selected song and no real medley.
 

Great, to be able to load a playlist to the main-area of "Sing"-section!
I wonder, what the options below each song in the playlist view is about:
![image](https://user-images.githubusercontent.com/20970069/73882398-43389d00-4862-11ea-80c7-32debe705bd6.png)

When being in Party-mode and selecting "song source"=Playlist, I have the feeling, that not the correct list is being used. May someone test?

Thanks a lot so far. I hope I have not pointed out too many findings. Should I report each finding to a separate issue?

Thanks a lot for your support...

**Comment by Stefan1200-de** [comment] 2020-02-05 21:38
@Michri 
1. You have a way to reproduce?
2. Well, you replaced that number sign (#) with a number (0-9), right?
3. Suggestions? Well, its not only artists grouping. It groups to the value how you sorted that list. So it can also group for language, decade, genre, folder, etc.
4. Search always search for artists and title, if you don't use the extended keywords (described at the bottom).
5. CTRL+S only start the selected song as a medley, and only if the selected song supports the medley game mode. Currently there is no error message if that is not possible.

You can select the game mode (Normal, Short version, Medley) for each playlist entry individually.

Please create an new issue, if my answers are not solving that question/problem.

**Comment by Michri** [comment] 2020-02-07 21:31
Hi @Stefan1200-de 

Thanks for clarification. That was helpful.

About @2 I do not understand the difference between CTRL+2 and CTRL+3 (Sorting: Artist / Sorting: Artist by letter).

I still do not get the settings in playlist:
![image](https://user-images.githubusercontent.com/20970069/74067084-b6741780-49f8-11ea-98cf-77653eba0361.png)
When will these settings take effect? What do I need to trigger, to get a medley based on the titles configured as medly in the playlist?

About partymode-playlist issue I will create a separate issue.

**Comment by Stefan1200-de** [comment] 2020-02-07 21:37
@Michri 
About 2: Activate the **tabs / category / grouping view** in the settings or with CTRL+T and you see the difference. Without it you don't need **Artist by letter**.

About the playlist stuff:
If you sing the playlist (the microphone icon in the lower toolbar of the playlist), it will play **Blue - One Love** as **normal** song, **Carl Douglas - Kung Fu Fighting** as **short** song and **Dido - Thank you** as **Medley**. Not more and not less. ;)

I don't understand your last question: "What do I need to trigger, to get a medley based on the titles configured as medly in the playlist?" What do you mean with that?

**Comment by Michri** [comment] 2020-02-07 21:47
I see, selecting "Medley" will play the selected song only, but in the really short medley version.

**Comment by Stefan1200-de** [comment] 2020-02-07 21:55
> I see, selecting "Medley" will play the selected song only, but in the really short medley version.

Well, except that "selected song only", that was because you clicked twice by accident and happens no matter what you have chosen (normal, short or medley). But yes, medley is the shortes version of the song, while short is just half as long as the normal song length.
